### ISSUE TITLE
Handling polyphonic submissions for the monophonic task

### ISSUE THREAD

**Issue by JamesOwers** [BeritJanssen/PatternsForPrediction#5]
Lines 57 and 58 in ./evaluate_prediction are unused. https://github.com/BeritJanssen/PatternsForPrediction/blob/master/evaluate_prediction.py#L57

Further down the file, the onsets are extracted again and, this time, `set` is not used to deduplicate them. In the case of the monophonic task, if this file was used as is for evaluation, the results may be incorrect if generated submissions were not monophonic (because the number of elements in the set Q will be larger => precision will be lower).

It is not stated that there should be a deduplication in the score as described [here](https://www.music-ir.org/mirex/wiki/2018:Patterns_for_Prediction#IOI). In the monophonic case, how would a polyphonic submission be handled? This would matter for the pitch scores; should both pitches be included if simultaneous notes were submitted?

**Comment by BeritJanssen** [comment]
I tested the code for monophonic and polyphonic submissions. If there is a polyphonic continuation to a monophonic prime, I would consider it fair that this gets lower precision.
