### ISSUE TITLE
Handling of scores for empty generations and empty true continuations

### ISSUE THREAD

**Issue by JamesOwers** [BeritJanssen/PatternsForPrediction#6]
Looking at Figure 3 in comparison to Figures 2 and 1 on the [results page](https://www.music-ir.org/mirex/wiki/2018:Patterns_for_Prediction_Results) I suspect that `NaN` values are being discounted, or that there are erroneously no `NaN` values being produced. I suspect this because it would be difficult for a model with an average precision of `.5` and average recall of `.5` to have an f1 score of nearly `1`. 

To put it another way, I expected the f1 curves to be the harmonic mean of the precision and recall curves!

I think the secret to why they are not lies in how the cases where not notes are present in either the generated melody, or the true melody up to the given onset time.

This is also affection the issue regarding precision and recall calculation (Issue #7 - Results are optimistic: if one of them is `NaN`, the other will be `NaN`, but should be 0).

I'm a bit confused as to why [Line #6](https://github.com/BeritJanssen/PatternsForPrediction/blob/master/Visualize_prec_recall.R#L6) of the Visualize_prec_recall.R script doesn't produce NaNs - if it did then i think [`geom_smooth`](https://ggplot2.tidyverse.org/reference/geom_smooth.html), as it's written on [line #25](https://github.com/BeritJanssen/PatternsForPrediction/blob/master/Visualize_prec_recall.R#L25) etc, would error (`na.rm` is set to FALSE by default), [line #70](https://github.com/BeritJanssen/PatternsForPrediction/blob/master/evaluate_prediction.py#L70). But it *should* produce NaNs, because its entirely possible for both precision and recall to be `0` at, say, `onset_time = 1`. I think the reason why the F1 is so high when the onset time is small is that, for a lot of cases, precision+recall = 0, and so the F1 is undefined. I argue the F1 should be 0 here - if both the recall and precision are 0, the F1 should also be 0!

Here is my proposal:

```
    When comparing a generated sequence of notes 
    with the true sequence of notes, if:
    1. the generated sequence is empty AND the true sequence is empty, 
       i.e. we predict nothing, and the true sequence is contains nothing
        * This is correct! So we give a precision, recall, and f1 of 1
    2. the generated sequence is empty BUT the true sequence is NOT
        * This is incorrect. We give a recall and f1 of 0
        * However, since we predict nothing, we give a precision of 0 - to give 
           a precision of NaN would advantage predicting nothing
    3. the true sequence is empty BUT the generated sequence is NOT
        * This is incorrect. We give a precision and f1 of 0
        * However, since there was nothing to predict, we give a
          recall of 0 - to give a recall of NaN would advantage predicting
          nothing
    4. the precision and recall are 0:
        * from the formula, f1 is undefined but, given the above conditions
          the only way we can get precision and recall of 0 is if we predict
          notes, and there were notes to predict, but there is no intersection
          between these two. That's clearly bad, so we give an f1 of 0.
          
    Note that point 4 above is important when considering averaging precision,
    recall, and f1 scores over the whole dataset: it is entirely possible to have
    a precision of 0 and a recall of 0, and thus an f1 of 0. If this is not
    handled explicitly, precision and recall of 0 could lead to an f1 of NaN.
    If, when averaging, we discount NaN values, this gives an overly
    optimistic score (the NaNs should have been 0s!).
```

**Comment by JamesOwers** [comment]
It's worth noting that, although [`geom_smooth`](https://ggplot2.tidyverse.org/reference/geom_smooth.html), as it's written on [line #25](https://github.com/BeritJanssen/PatternsForPrediction/blob/master/Visualize_prec_recall.R#L25) etc, would error if provided with missing values (`na.rm` is set to FALSE by default), [line #70](https://github.com/BeritJanssen/PatternsForPrediction/blob/master/evaluate_prediction.py#L70) in the evaluation script means that no missing values are ever produced.

**Comment by JamesOwers** [comment]
I'm sorry for the quick succession of messages, but my proposal of filling `NaN`s with zeros is definitely not good! It leads to an overly pessimistic average score. I think some cases are legitimately NaN, but in the case of the F1 score, this is not the case. Here is my proposal:

```
When comparing a generated sequence of notes 
    with the true sequence of notes, if:
    1. the generated sequence is empty AND the true sequence is empty, 
       i.e. we predict nothing, and the true sequence is contains nothing
        * This is correct! So we give a precision, recall, and f1 of 1
    2. the generated sequence is empty BUT the true sequence is NOT
        * This is incorrect. We give a recall and f1 of 0
        * However, since we predict nothing, we give a precision of NaN
    3. the true sequence is empty BUT the generated sequence is NOT
        * This is incorrect. We give a precision and f1 of 0
        * However, since there was nothing to predict, we give a
          recall of NaN
    4. the precision and recall are 0:
        * from the formula, f1 is undefined but, given the above conditions
          the only way we can get precision and recall of 0 is if we predict
          notes, and there were notes to predict, but there is no intersection
          between these two. That's clearly bad, so we give an f1 of 0.
          
    Note that point 4 above is important when considering averaging precision,
    recall, and f1 scores over a dataset: it is entirely possible to have
    a precision of 0 and a recall of 0, and thus an f1 of 0. If this is not
    handled explicitly, precision and recall of 0 could lead to an f1 of NaN.
    If, when averaging, we discount NaN values, this gives an overly
    optimistic score (the NaNs should have been 0s!).
```

**Comment by JamesOwers** [comment]
I've reimplemented your score code and evaluated the cont_foil data against the cont_true data. I've also implemented the proposal I've outlined in the top statement. The results are shown below. The scores, as implemented and published on [the results page](https://www.music-ir.org/mirex/wiki/2018:Patterns_for_Prediction_Results) are labeled `published_scores`. Scores calculated with my proposed changes are labelled `revised_scores`.

The main effects are:
* Increased precision and recall for low values of t; this is because correctly predicting nothing is now credited
* Decreased f1; this is because having a precision and recall both being 0 results in an f1 of 0

![image](https://user-images.githubusercontent.com/3524723/51696757-1a9a8800-1ffe-11e9-91a5-eb4cf5416754.png)

![screenshot from 2019-01-24 17 39 01](https://user-images.githubusercontent.com/3524723/51697101-f25f5900-1ffe-11e9-8e79-b6c66953749c.png)

![screenshot from 2019-01-24 17 39 22](https://user-images.githubusercontent.com/3524723/51697114-f5f2e000-1ffe-11e9-845e-391a1d36f1d7.png)

**Comment by BeritJanssen** [comment]
Thank you, James! I will certainly revisit the evaluation code soon. Can you PR your changes?

**Comment by JamesOwers** [comment]
Hi @BeritJanssen - sure, I'll probably be a couple of weeks. Do you need it sooner than that?

**Comment by BeritJanssen** [comment]
Hi James, did you work on this in the meantime? I just made some modifications to the Python script. I also moved calculation of F1 to Python, will modify the R scripts accordingly. If you have time to look at this PR (#8 ), that would be very welcome.

**Comment by JamesOwers** [comment]
Hi Berit - apologies, I've not had time to do this as yet.

I've scanned the PR and it looks good. I've put together a gist with my code which you should be able to adapt to check we get the same numbers (just change lines 254-256 for it to run for you): 
https://gist.github.com/JamesOwers/afc8163f4a5da84587079147bb9bf9a0

Apologies I don't have more time right now to look at this in detail.

**Comment by BeritJanssen** [comment]
Hi James,
thank you for sharing your code. I had actually been meaning to work with seaborn when I wrote the evaluation scripts, but struggled with it, so switched to R instead. So it was great to see a working example, thanks!

I actually adopted the use of tqdm and seaborn in another branch (#9), trying a different approach to evaluation. I hope you are okay with this? I will add a GNU license to the repository, so if you'd rather the code didn't become open source, please let me know.

**Comment by JamesOwers** [comment]
Go for it, it's all yours. I'm also to help in future as I'm actively
working on this. Please feel free to tag me in as you like.
